#!/bin/sh
# Writes compose.override.yaml with one read-only mount per folder listed in .env
# (MARUMADO_PROJECT_DIRS, scanned, and MARUMADO_MOUNTS, only made visible so they
# can be added in the app). Folders keep their host path, so process folders match.
# `make up` runs this; compose picks the override file up on its own.
set -eu
# Read the two values without sourcing .env (paths may contain spaces).
env_value() { [ -f .env ] && sed -n "s/^$1=//p" .env | tail -n 1 | sed 's/^["'\'']//; s/["'\'']$//'; }
projects=$(env_value MARUMADO_PROJECT_DIRS)
dirs="${projects:-/projects},$(env_value MARUMADO_MOUNTS)"

{
  echo "# Generated by scripts/compose-mounts.sh from .env. Do not edit; run make up."
  echo "services:"
  echo "  marumado:"
  echo "    volumes:"
  echo "$dirs" | tr ',' '\n' | sed 's/^ *//; s/ *$//; s:/*$::' | grep -v '^$' | sort -u | while IFS= read -r d; do
    case "$d" in
      /*) ;;
      *) echo "compose-mounts: skipping '$d' (use a full path)" >&2; continue ;;
    esac
    [ -d "$d" ] || echo "compose-mounts: warning: '$d' does not exist on this machine" >&2
    esc=$(printf '%s' "$d" | sed 's/"/\\"/g')
    echo "      - \"$esc:$esc:ro\""
  done
  # SSH keys, for MARUMADO_HERDR_SSH and for other machines in the Machines module
  # (set MARUMADO_SSH_DIR for those). Then Herdr's local socket and binary.
  ssh_dir=$(env_value MARUMADO_SSH_DIR)
  if [ -n "$ssh_dir" ] || [ -n "$(env_value MARUMADO_HERDR_SSH)" ]; then
    ssh_dir=${ssh_dir:-$HOME/.ssh}
    case "$ssh_dir" in "~"*) ssh_dir="$HOME${ssh_dir#\~}" ;; esac
    [ -d "$ssh_dir" ] || echo "compose-mounts: warning: '$ssh_dir' does not exist on this machine" >&2
    echo "      - \"$ssh_dir:/root/.ssh:ro\""
  fi
  for f in "$(env_value MARUMADO_HERDR_SOCKET)" "$(env_value MARUMADO_HERDR_BIN)"; do
    if [ -n "$f" ]; then echo "      - \"$f:$f\""; fi
  done
  # smolvm: your install and machine state, at the same paths, used as you (see core/herdr.py).
  if [ -n "$(env_value MARUMADO_HERDR_SMOLVM)" ]; then
    data="${XDG_DATA_HOME:-$HOME/.local/share}/smolvm"
    for d in "$HOME/.smolvm:ro" "$data"; do
      [ -d "${d%:ro}" ] || echo "compose-mounts: warning: '${d%:ro}' not found; is smolvm installed?" >&2
      echo "      - \"${d%:ro}:$d\""
    done
    cache="${XDG_CACHE_HOME:-$HOME/.cache}/smolvm"
    if [ -d "$cache" ]; then echo "      - \"$cache:$cache\""; fi
    echo "    environment:"
    echo "      MARUMADO_SMOLVM_HOME: \"$HOME\""
    echo "      MARUMADO_SMOLVM_USER: \"$(id -u):$(id -g)\""
  fi
} > compose.override.yaml
