#!/bin/sh
# Writes compose.override.yaml with one read-only mount per folder listed in .env
# (MARUMADO_PROJECT_DIRS, scanned, and MARUMADO_MOUNTS, only made visible so they
# can be added in the app). Folders keep their host path, so process folders match.
# `make up` runs this; compose picks the override file up on its own.
set -eu
# Read the values without sourcing .env (paths may contain spaces).
env_value() { if [ -f .env ]; then sed -n "s/^$1=//p" .env | tail -n 1 | sed 's/^["'\'']//; s/["'\'']$//'; fi; }
env_set() { [ -f .env ] && grep -q "^$1=" .env; }
# Most machines (servers) have no projects of their own. Unset: /projects, only if this machine has it.
# Set but empty: no project folders at all.
if env_set MARUMADO_PROJECT_DIRS; then
  projects=$(env_value MARUMADO_PROJECT_DIRS)
elif [ -d /projects ]; then
  projects=/projects
else
  projects=
fi
dirs="$projects,$(env_value MARUMADO_MOUNTS)"

# Only folders that exist are mounted: Docker would otherwise create them, empty and owned by root.
mounts=$(echo "$dirs" | tr ',' '\n' | sed 's/^ *//; s/ *$//; s:/*$::' | { grep -v '^$' || true; } | sort -u | while IFS= read -r d; do
  case "$d" in
    /*) ;;
    *) echo "compose-mounts: skipping '$d' (use a full path)" >&2; continue ;;
  esac
  if [ ! -d "$d" ]; then
    echo "compose-mounts: '$d' isn't on this machine, so it isn't mounted" >&2
    continue
  fi
  esc=$(printf '%s' "$d" | sed 's/"/\\"/g')
  echo "      - \"$esc:$esc:ro\""
done)

{
  echo "# Generated by scripts/compose-mounts.sh from .env. Do not edit; run make up."
  echo "services:"
  echo "  marumado:"
  echo "    volumes:"
  # Always one entry, so the list is never empty (the data volume is in compose.yaml too; repeating it is harmless).
  echo "      - marumado-data:/app/backend/data"
  if [ -n "$mounts" ]; then echo "$mounts"; fi
  environment="      MARUMADO_PROJECT_DIRS: \"$(printf '%s' "$projects" | sed 's/"/\\"/g')\"
"
  # SSH keys, for MARUMADO_HERDR_SSH and for other machines in the Machines module
  # (set MARUMADO_SSH_DIR for those). Then Herdr's local socket and binary.
  ssh_dir=$(env_value MARUMADO_SSH_DIR)
  if [ -n "$ssh_dir" ] || [ -n "$(env_value MARUMADO_HERDR_SSH)" ]; then
    ssh_dir=${ssh_dir:-$HOME/.ssh}
    case "$ssh_dir" in "~"*) ssh_dir="$HOME${ssh_dir#\~}" ;; esac
    ssh_dir=${ssh_dir%/}
    [ -d "$ssh_dir" ] || echo "compose-mounts: warning: '$ssh_dir' does not exist on this machine" >&2
    # At its host path, so absolute paths in its config resolve. ssh refuses a config owned by another
    # user, so Marumado copies it into root's ~/.ssh before each ssh call (core/sshhome.py).
    echo "      - \"$ssh_dir:$ssh_dir:ro\""
    # ssh in the container is root; log in as you by default, like ssh on the host.
    environment="$environment      MARUMADO_SSH_SOURCE: \"$ssh_dir\"
      MARUMADO_SSH_USER: \"$(id -un)\"
"
  fi
  for f in "$(env_value MARUMADO_HERDR_SOCKET)" "$(env_value MARUMADO_HERDR_BIN)"; do
    if [ -n "$f" ]; then echo "      - \"$f:$f\""; fi
  done
  # smolvm: your install and machine state, at the same paths, used as you (see core/herdr.py). Whenever
  # it is installed, so smolvm machines added in the app (Agents → Sources) work too.
  if [ -n "$(env_value MARUMADO_HERDR_SMOLVM)" ] || [ -d "$HOME/.smolvm" ]; then
    data="${XDG_DATA_HOME:-$HOME/.local/share}/smolvm"
    for d in "$HOME/.smolvm:ro" "$data"; do
      [ -d "${d%:ro}" ] || echo "compose-mounts: warning: '${d%:ro}' not found; is smolvm installed?" >&2
      echo "      - \"${d%:ro}:$d\""
    done
    cache="${XDG_CACHE_HOME:-$HOME/.cache}/smolvm"
    if [ -d "$cache" ]; then echo "      - \"$cache:$cache\""; fi
    environment="$environment      MARUMADO_SMOLVM_HOME: \"$HOME\"
      MARUMADO_SMOLVM_USER: \"$(id -u):$(id -g)\"
"
  fi
  if [ -n "$environment" ]; then printf '    environment:\n%s' "$environment"; fi
} > compose.override.yaml
