"""
Django settings for marumado project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import re
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env(name, default=''):
    """The MARUMADO_<name> environment variable."""
    return os.environ.get(f'MARUMADO_{name}', default)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', 'django-insecure-local-only-marumado')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', '0') == '1'

ALLOWED_HOSTS = env('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.StartMonitor',
]

ROOT_URLCONF = 'marumado.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'marumado.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'data' / 'marumado.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Built frontend (frontend/dist) is served at / by WhiteNoise in production mode.
FRONTEND_DIST = BASE_DIR.parent / 'frontend' / 'dist'
WHITENOISE_ROOT = FRONTEND_DIST if FRONTEND_DIST.exists() else None
WHITENOISE_INDEX_FILE = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': ['core.permissions.MarumadoToken'],
    'UNAUTHENTICATED_USER': None,
}

# --- Marumado ---
# Folders whose subfolders are projects, separated by commas (or colons). More can be added in the app.
# Unset: /projects, only when this machine has it. Set empty: none (a server with no projects of its own).
_project_dirs = os.environ.get('MARUMADO_PROJECT_DIRS', os.environ.get('MARUMADO_PROJECT_ROOTS'))
MARUMADO_PROJECT_ROOTS_DEFAULT = _project_dirs is None
MARUMADO_PROJECT_ROOTS = [
    Path(p.strip()).expanduser()
    for p in re.split(r'[,:]', '/projects' if _project_dirs is None else _project_dirs) if p.strip()
]
# The access token, always required (see core/auth.py). When unset, one is made on first run and kept in
# data/access-token. Browsers log in with it once; other Marumados send `Authorization: Bearer <token>`.
MARUMADO_TOKEN = env('TOKEN', '').strip()

# The browser's login. Cookies ignore ports, so the port keeps two Marumados (or another Django app) on one host apart.
SESSION_COOKIE_NAME = f"marumado_{env('PORT', '7878')}"
SESSION_COOKIE_AGE = 30 * 24 * 3600
SESSION_COOKIE_SAMESITE = 'Strict'
SESSION_COOKIE_HTTPONLY = True
MARUMADO_SAMPLE_SECONDS = float(env('SAMPLE_SECONDS', '2'))
MARUMADO_HISTORY_POINTS = int(env('HISTORY_POINTS', '900'))  # 30 min at 2s
MARUMADO_UPTIME_SECONDS = float(env('UPTIME_SECONDS', '60'))


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
