# Generated by Django 6.1.1 on 2026-10-01 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('path', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('local_url', models.URLField(blank=True, default='')),
                ('online_url', models.URLField(blank=True, default='')),
                ('repo_url', models.URLField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('pinned', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('scan', 'Scanned'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('detected', models.JSONField(blank=True, default=dict)),
                ('locked_fields', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-pinned', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('path', ''), _negated=True), fields=('path',), name='unique_project_path')],
            },
        ),
        migrations.CreateModel(
            name='UptimeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('local', 'Local'), ('online', 'Online')], max_length=10)),
                ('url', models.URLField()),
                ('ok', models.BooleanField()),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('error', models.CharField(blank=True, default='', max_length=300)),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='core.project')),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['project', 'target', '-checked_at'], name='core_uptime_project_237422_idx')],
            },
        ),
    ]
