# Generated by Django 6.1.1 on 2026-10-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_scanroot'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='kind',
            field=models.CharField(choices=[('project', 'Project'), ('link', 'Link')], default='project', max_length=10),
        ),
    ]
