# Generated by Django 6.1.1 on 2026-10-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('intent', models.CharField(blank=True, choices=[('', 'No plan'), ('learn', 'Want to learn'), ('grow', 'Growing'), ('ignore', 'Not a skill')], default='', max_length=10)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='focus',
            field=models.CharField(blank=True, choices=[('', 'Undecided'), ('push', 'Push'), ('park', 'Park')], default='', max_length=10),
        ),
    ]
