# Generated by Django 6.1.1 on 2026-10-02 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('state', models.CharField(choices=[('todo', 'To do'), ('starting', 'Starting'), ('working', 'Working'), ('blocked', 'Needs you'), ('review', 'To review'), ('done', 'Done'), ('failed', 'Failed')], default='todo', max_length=10)),
                ('pane_id', models.CharField(blank=True, default='', max_length=40)),
                ('agent_name', models.CharField(blank=True, default='', max_length=40)),
                ('agent_kind', models.CharField(blank=True, default='', max_length=20)),
                ('agent_state', models.CharField(blank=True, default='', max_length=10)),
                ('agent_title', models.CharField(blank=True, default='', max_length=200)),
                ('live', models.BooleanField(default=False)),
                ('git_start', models.CharField(blank=True, default='', max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.project')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('kind', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('prompt', 'Prompt sent'), ('state', 'Agent state'), ('activity', 'Activity'), ('changes', 'Changes'), ('closed', 'Pane closed'), ('error', 'Error'), ('done', 'Marked done'), ('reopened', 'Reopened')], max_length=10)),
                ('state', models.CharField(blank=True, default='', max_length=10)),
                ('text', models.CharField(blank=True, default='', max_length=500)),
                ('output', models.TextField(blank=True, default='')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.task')),
            ],
            options={
                'ordering': ['at', 'id'],
            },
        ),
    ]
