# Generated by Django 6.1.1 on 2026-10-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='prompt_pending',
            field=models.BooleanField(default=False),
        ),
    ]
