# Generated by Django 6.1.1 on 2026-10-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_task_event_moved'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('kind', models.CharField(choices=[('ssh', 'SSH'), ('smolvm', 'smolvm machine')], default='ssh', max_length=10)),
                ('target', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='agent_source',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
