# Generated by Django 6.1.1 on 2026-10-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_agent_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='agent_cwd',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='task',
            name='transcript',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
