# Generated by Django 6.1.1 on 2026-10-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_task_trace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=60, unique=True)),
                ('value', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='agentsource',
            name='folders',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
