# Generated by Django 6.1.1 on 2026-10-05 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_source_folders'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='plan_col',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='plan_row',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='runner',
            field=models.CharField(blank=True, choices=[('', 'Continue'), ('new', 'New agent'), ('agent', 'This agent')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='task',
            name='want_pane',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='task',
            name='want_source',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='worktree',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('todo', 'To do'), ('queued', 'Queued'), ('starting', 'Starting'), ('working', 'Working'), ('blocked', 'Needs you'), ('review', 'To review'), ('done', 'Done'), ('failed', 'Failed')], default='todo', max_length=10),
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(default='claude', max_length=20)),
                ('source', models.PositiveIntegerField(default=0)),
                ('running', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='core.project')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='core.plan'),
        ),
    ]
