# Generated by Django 6.1.1 on 2026-10-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='pane_id',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='plan',
            name='pane_source',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='ask',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='go',
            field=models.BooleanField(default=False),
        ),
    ]
