# Generated by Django 6.1.1 on 2026-10-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_task_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskevent',
            name='kind',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('prompt', 'Prompt sent'), ('state', 'Agent state'), ('activity', 'Activity'), ('changes', 'Changes'), ('closed', 'Pane closed'), ('error', 'Error'), ('done', 'Marked done'), ('reopened', 'Reopened'), ('moved', 'Moved'), ('archived', 'Archived'), ('restored', 'Restored')], max_length=10),
        ),
    ]
