# Generated by Django 6.1.1 on 2026-10-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='agent_source',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
