# Generated by Django 6.1.1 on 2026-10-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_project_agent_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
