# Generated by Django 6.1.1 on 2026-10-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_plan_start_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='check_command',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='plan',
            name='check_fixes',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='task',
            name='check_state',
            field=models.CharField(blank=True, choices=[('', 'Not run'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed'), ('fixing', 'Being fixed'), ('skipped', 'Not checked')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='check_tries',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='landed',
            field=models.CharField(blank=True, choices=[('', 'Not yet'), ('merged', 'Merged'), ('discarded', 'Discarded')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='pr_url',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='task',
            name='usage',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskevent',
            name='kind',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('prompt', 'Prompt sent'), ('state', 'Agent state'), ('activity', 'Activity'), ('changes', 'Changes'), ('closed', 'Pane closed'), ('error', 'Error'), ('done', 'Marked done'), ('reopened', 'Reopened'), ('moved', 'Moved'), ('archived', 'Archived'), ('restored', 'Restored'), ('check', 'Check'), ('feedback', 'Sent back'), ('merged', 'Merged'), ('pr', 'Pull request'), ('discarded', 'Discarded')], max_length=10),
        ),
    ]
